comment: false

codecov:
  token: 96fd7467-69dd-4522-aa47-26964809369e

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 1%
        informational: true
    patch:
      default:
        target: auto
        threshold: 1%
        informational: true
